### ISSUE TITLE
Please support the BSD sed

### ISSUE THREAD

**Issue by yurivict** [SoptikHa2/desed#10]

**Comment by yurivict** [comment]
Ideally, on BSD it should be able to debug both BSD ```sed``` and GNU ```gsed```, maybe based on the command argument.

**Comment by SoptikHa2** [comment]
Does this work with BSD `sed`, not the gnu version? I thought it will not work at all, and didn't test it, but now when I'm looking to manpages, there doesn't seem to be a reason this shouldn't work.

I can certainly provide a way to call different program instead of sed, maybe something like `--binary-name=gsed`?

**Comment by yurivict** [comment]
At least a ```sed``` command invocation causes a failure, see https://github.com/SoptikHa2/desed/issues/9

**Comment by SoptikHa2** [comment]
It looks like `sed` doesn't like being invoked the way desed does. Does this work?

```
sed --debug -f x.sed input.txt
sed -E --debug -f x.sed input.txt
```

It works for me when I run sed in posix mode.

Anyway, if you build from source, I added some debug printing (use `--debug`) that clearly describes how is sed executed (some actually useful debug info coming soon) and option to specify what to execute with `--sed-path=gsed`. I'll add those to a release when I fix at least #9.

**Comment by yurivict** [comment]
> Does this work?

No:

```
[yuri@yv /tmp]$ sed --debug -f x.sed input.txt
sed: illegal option -- -
usage: sed script [-Ealnru] [-i extension] [file ...]
	sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
[yuri@yv /tmp]$ sed -E --debug -f x.sed input.txt
sed: illegal option -- -
usage: sed script [-Ealnru] [-i extension] [file ...]
	sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Comment by SoptikHa2** [comment]
Thank you for testing. Unfortunately there is no way desed is going to work with BSD sed - I need the extra information that I get from usage of the `—debug` flag.

If that’s all I’ll close this when I release new version with the `—sed-path` option. I’ll look into way to detect early that something went wrong and try to use `gsed` automatically.

**Comment by yurivict** [comment]
```gsed``` and ```sed``` are different programs on BSDs.

```sed``` apparently has different invocation arguments. It would be best if ```desed``` would support both programs.

**Comment by SoptikHa2** [comment]
Unfortunately I need debug output from sed. With gnu sed it's achieved with the `--debug` flag, which prints detailed annotation of what sed does. If BSD `sed` doesn't have it, I can't do anything. If there is something like that, maybe under different flag, let me know and I'll add it.

For now, I've added automatic fallback to `gsed` if `sed` fails, so if you have both programs installed, it should work out of the box and you won't even notice it. One can override this behaviour with `--sed-path`.
