### ISSUE TITLE
Add some way to notify Desed to reload code from outside

### ISSUE THREAD

**Issue by SoptikHa2** [SoptikHa2/desed#12]
I would like to integrate this with [`entr(1)`](https://eradman.com/entrproject/), which allows user to run arbitrary commands when file changes. I imagine we could use this to automatically reload desed when source code changes. The way it's implemented now user has to press `l` manually which is annoying.

Possibly somehow listen for signal?

**Comment by suve** [comment]
On Linux, this could be done using [inotify](https://linux.die.net/man/7/inotify). I have close to zero experience with BSDs, but a quick search on the internets suggests using [kqueue](https://man.bsd.lv/kqueue.2). Both of these seem to have rust wrapper crates available for them, so one could try writing some thin abstraction layer above those.

**Comment by SoptikHa2** [comment]
This looks great, thanks! The priority is currently rewriting the parsing system (try any sed program with lots of newlines in regexes and such and you will discover tons of bugs) into something sensible, but these look really nice. I didn't look into the crates yet, but I really like the idea and would like to use this.

Thanks!

Relevant links:
[inotify crate](https://crates.io/crates/inotify)
[kqueue crate](https://crates.io/crates/kqueue)
[dependencies that vary per platform](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies)
[code that vary per platform](https://doc.rust-lang.org/reference/conditional-compilation.html#forms-of-conditional-compilation)
