### ISSUE TITLE
Licensing: GPLv3-only / GPLv3-or-later?

### ISSUE THREAD

**Issue by suve** [SoptikHa2/desed#16]
Hi. I'm packaging `desed` for Fedora and want to make sure what to put in the `License:` section of the package specification. I've looked through the source and couldn't find an answer.

**Comment by SoptikHa2** [comment]
Hi, wonderful! Would you mind letting me know when it's done?

Currently the code is licensed as [GPLv3](https://github.com/SoptikHa2/desed/blob/master/LICENSE), I don't mention it anywhere in the code, but the license file should be at the root of the project.

**Comment by suve** [comment]
Yes, the license file is there. Typically, GPL-licensed projects follow the "or later" model, which in this case would mean "GPLv3 or any later version" - so if GPLv4 is published one day, it would be fine to use `desed` code under GPLv4.

So what I'm asking is if `desed` is "GPLv3 only" or "GPLv3 or any later version".

**Comment by SoptikHa2** [comment]
Ah, right. I didn't hear about the `or later` variant before, but it's fine by me. 

Thanks for reaching out, I'll update `Cargo.toml` to specify GPLv3 or later.

**Comment by suve** [comment]
The "How to apply these terms to your new programs" section at the end of GPL even suggests this:
```
To do so, attach the following notices to the program. [...]

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
```
Some people opt out of this, explicitly marking their stuff as GPLv3 **only**, so I wanted to clarify. Thanks!

**Comment by SoptikHa2** [comment]
Glad to help! Thanks for packaging Desed. Please let me know when you do it, so I can link it from readme.

**Comment by suve** [comment]
Desed is now [packaged](https://src.fedoraproject.org/rpms/rust-desed) and available in Fedora Rawhide (the development release); it will appear in F32 and F31 in about a week, once it makes it [out of testing](https://bodhi.fedoraproject.org/updates/?packages=rust-desed).
