### ISSUE TITLE
This supposed to be a joke?!

### ISSUE THREAD

**Issue by jirutka** [SoptikHa2/desed#23]
> Is this a joke?
> I thought it was. But apparently it's actually useful for some people.

Are you kidding me? :smile: This tool is super-useful!

I wish you’d written it a few years when I was hacking this insanity: [dokuwiki2adoc](https://github.com/jirutka/dokuwiki2adoc) (I used it to convert thousands of EDUX pages to Courses/AsciiDoc).

**Comment by SoptikHa2** [comment]
Glad you like it :D

I still find it unbelievable that people actually write that huge sed scripts, instead to trying at least awk or something similar.
But yeah, then someone comes and codes [this](https://tildes.net/~comp/b2k/programming_challenge_find_path_from_city_a_to_city_b_with_least_traffic_controls_inbetween#comment-2run).

Wonderful that you managed to fix it without proper tooling. GNU sed has a debug mode, but the interface was unusable for me :smile:

**Comment by SoptikHa2** [comment]
(which reminds me, I should probably finally rewrite the parser to properly handle literal newlines in regex patterns. It sometimes confuses the whole parser :smile:)
