### ISSUE TITLE
Please update kqueue to at least 1.0.6?

### ISSUE THREAD

**Issue by yurivict** [SoptikHa2/desed#24]
This is to avoid [this](https://gitlab.com/rust-kqueue/rust-kqueue-sys/-/issues/3) problem.

**Comment by SoptikHa2** [comment]
Will do as soon as I finish some work for my university courses, which should be at wednesday hopefully.

I want to update all the dependencies, so I may just do it everything at once while I'm at it. And there's been some breaking changes, so it'll take me a while.

**Comment by SoptikHa2** [comment]
It is done, I'll update the cargo package and AUR package in few minutes.

**Comment by yurivict** [comment]
Thanks!
